// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCscdl9QOc9-BNkfRu7LgGMLUXMzh9U6_U',
    appId: '1:487535833101:web:1012a926a01ed41535a544',
    messagingSenderId: '487535833101',
    projectId: 'grocery-delivery-54e0e',
    authDomain: 'grocery-delivery-54e0e.firebaseapp.com',
    storageBucket: 'grocery-delivery-54e0e.appspot.com',
    measurementId: 'G-4EMWZ95NHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWNMaeQOUgM3CdjjPNTwmYxTyAZCY7fOM',
    appId: '1:487535833101:android:77da107c77afbaa035a544',
    messagingSenderId: '487535833101',
    projectId: 'grocery-delivery-54e0e',
    storageBucket: 'grocery-delivery-54e0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApZtkLNmFzGCIpClBHf5JyxR2auiA3PRI',
    appId: '1:487535833101:ios:d2c1f78ccd09530d35a544',
    messagingSenderId: '487535833101',
    projectId: 'grocery-delivery-54e0e',
    storageBucket: 'grocery-delivery-54e0e.appspot.com',
    iosClientId: '487535833101-v1nrm92gvtob7jsf0j7s6nlbq10doucj.apps.googleusercontent.com',
    iosBundleId: 'com.mervenurtopcu.grocerydelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApZtkLNmFzGCIpClBHf5JyxR2auiA3PRI',
    appId: '1:487535833101:ios:d2c1f78ccd09530d35a544',
    messagingSenderId: '487535833101',
    projectId: 'grocery-delivery-54e0e',
    storageBucket: 'grocery-delivery-54e0e.appspot.com',
    iosClientId: '487535833101-v1nrm92gvtob7jsf0j7s6nlbq10doucj.apps.googleusercontent.com',
    iosBundleId: 'com.mervenurtopcu.grocerydelivery',
  );
}
